# Generated by Django 4.1.1 on 2022-09-30 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='samplemodel',
            unique_together=set(),
        ),
    ]
