# Generated by Django 4.1.1 on 2022-09-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_alter_samplemodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='samplemodel',
            unique_together={('name', 'char_field', 'decimal_field', 'integer_field', 'boolean_field')},
        ),
    ]
