# Generated by Django 4.1.1 on 2022-10-03 02:42

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_userotp_useraccount_user_app_us_usernam_917da3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='400', message='Please enter a phone number without the ISD code.', regex=re.compile('^([\\s.-])?(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?([\\s.-])?\\d{3}([\\s.-])?\\d{4}$'))]),
        ),
    ]
